### ISSUE TITLE
Fighting with margins and padding

### ISSUE THREAD

**Issue by char1129** [char1129/sections#1]
@thomasjbradley @char1129 

Hello Professor Thomas,

Do you have any tips when it comes to this assignment? I've been tinkering with this for a few days now and haven't seemed to make any headway. I also went to a lab with Holly and Sara S on Wednesday to make headway, and we did - but I feel like I need to start from scratch a third time because I can't seem to figure it. The html is sound - css 'ain't' as pretty.

The body which I'm pretty sure should have a margin value of 0 is coming up wrong in Markbot. .5rem - 2em all come up as wrong values for margin in the body tag, auto as well.
I've had two green beautiful confirmations out of the 5 photos, a fluke because I can't seem to replicate that now... else I am able to get close to the 13% on either landscape or portrait, but not both at the same time.

I have a think that overall css should look/work like this:
**html tag:** overall background/font color/font weight/font family/margin and line height. 
**body:** margin: 0; minor padding
**selection:** text-align: centre
**.image:** display: inline-block, max width, vertical align, and padding (? because it'll move the image within the box as the screen dimensions change)
**img**: display: block width 100%
.paragraph: display: inline-block, max width, vertical align, text align padding (?because of the same reasons above)
**h2:** font-weight, font-size, margin (? to space it from img and p tags, also will be absorbed by larger margin of body when in landscape)
**p:** padding
**.btn:** border, border-radius, padding, text align
**a:** text decoration: none, color
**a:hover:** color #fff, background colour

Any advice, critiques or corrections you could suggest would be greatly appreciated.

Thank you.
Sarah Charity

**Comment by thomasjbradley** [comment]
Yeah, the HTML is perfect.

The CSS is a little over complicated, here are some adjustments:

1. Remove the padding from: `body`, `h2`, `p`
2. Remove the margin from : `html`, `section`, `.image`, `.paragraph`
3. `.image` & `.paragraph` should have `padding: 1em`
4. `section` should have padding only on its top & bottom: `padding: 2em 0`
5. The `h2` & `p` should have margins only on their bottom, like this: `margin: 0 0 1.5rem`

**Comment by char1129** [comment]
@thomasjbradley @char1129

Thank you for the help! I've made the changes and now I am just struggling with Markbot's margin requirement. It says Line 15: Expected to see _margin_ with a different value inside _body_ _{}_
As per your notes, margins are 1.5rem. 
I think I have tired every combination under the sun. 1.5rem, 0 0 0 1.5rem, 1.5rem 0 0 0, ...etc 
0 0 1.5rem puts me at the closest percentage of 17% on 960p with every other image's min requirement satisfied. I've also tried auto, 0 auto, inherit, and .5, .75 and 1.0rem, and 24px just incase a different value was needed.

I then tried to look at other areas of my document, keeping your advice in mind to see if I could adjust the inputs to modify the percentage, without much luck - even though that wouldn't solve the Markbot Body-Margin error.

I hate to ask again because I was really hoping to solve this myself, are there any other hints can you offer? Am I right thinking its 1.5rem? Is it just a certain sequence?
 
I feel like the IMG tag may also hold the key, but any adjustments I make to that make the box smaller and bot bigger don't seem to be effective, such as a margin-bottom of .5rem I managed to insert without disrupting any of the already satisfied screenshots.

(see attached image)
<img width="1420" alt="Screen Shot 2019-10-12 at 7 36 45 PM" src="https://user-images.githubusercontent.com/55107755/66709084-a38f5600-ed2a-11e9-894d-b5c01f215255.png">

Thank you.
Sarah

**Comment by char1129** [comment]
I spoke to a few classmates, and their markbot accepted body { margin= 0; }. I assume that I have to satisfy the last image first before I can enter margin = 0 to be accepted. I'll work on that tonight and update later. **Happy Thanksgiving!**

**Comment by char1129** [comment]
I cannot for the life of me close the gap of 960p requirement from 16 to 13% and figure out why a value of 0 for body margin does not work. After racking my brain over this for hours, I must admit defeat and move onto other assignments that need my attention. 
Thank you for your help Professor Thomas.
I do understand what this assignment was trying to teach, so thats good! Hopefully I have better luck with the next assignments. *fingers crossed*

**Comment by thomasjbradley** [comment]
Try this:

- The `<a>` tag should be `display: inline-block` & then won’t need any margins on it.
- Remove the margin from the bottom of the `<img>`
- Add `line-height: 1.5` to the `<html>` element

**Comment by char1129** [comment]
@thomasjbradley @char1129 

Managed to figure it out with 1 MINUTE TO SPARE!
Thank you for all your help! Heres to never giving up!
<img width="1319" alt="Screen Shot 2019-10-14 at 12 01 51 PM" src="https://user-images.githubusercontent.com/55107755/66765687-76ea5400-ee7a-11e9-8378-9d6f1314d114.png">

**Comment by thomasjbradley** [comment]
As I specified in my email, the assignments are due until after reading week. So, please don’t stress about it.

**Comment by char1129** [comment]
> As I specified in my email, the assignments are due until after reading week. So, please don’t stress about it.

Oh! I thought that meant for everything given this week! Your website still has this listed as due Oct 14th (and I read the military time wrong, its due at 2pm) oh well! At least you see I'm working hard!

Have a good day :)
